In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

def read_first_existing(*paths):
    for p in paths:
        if os.path.exists(p):
            return pd.read_pickle(p)
    raise FileNotFoundError(f"None of these files exists: {paths}")

In [2]:
path = 'E:/yjz/Extension for hts/JayCode/Models/'
base = pd.concat([
    read_first_existing("lgbInvtSim_L1.pkl", "lgbInvtSim_L1.pkl"),
    read_first_existing("etsInvtSim_L1.pkl", "etsInvtSim_L1.pkl")
], ignore_index=True)
bu   = read_first_existing("BUOrder_L1.pkl", "BUOrder_L1.pkl")
tdfp = read_first_existing("TDFPOrder_L1.pkl", "TDFPOrder_L1.pkl")
mint = read_first_existing("VarOrder_L1.pkl", "VarOrder_L1.pkl")

uid  = pd.read_pickle(f"{path}721future_28.pkl")
tag  = pd.read_pickle(f"{path}tags.bin")
try:
    ao = read_first_existing("actual_order.pkl")
except FileNotFoundError:
    ao = None

In [4]:
bu

,name,true_demand,forecasts,sst_90,arrival_90,ot_90,wip_90,ip_90,net_90,backlog_90,...,cb_95,sst_99,arrival_99,ot_99,wip_99,ip_99,net_99,backlog_99,ch_99,cb_99
0,lgb_base,4.0,5.689794,5.648312,0.000000,15.747402,1.574740e+01,17.437196,1.689794,0.0,...,0.0,10.253148,0.000000,28.585611,28.585611,30.275405,1.689794,0.0,1.689794,0.0
1,lgb_base,5.0,4.679130,5.648312,15.747402,4.350416,4.350416e+00,16.787612,12.437196,0.0,...,0.0,10.253148,28.585611,4.350416,4.350416,29.625822,25.275405,0.0,25.275405,0.0
2,lgb_base,7.0,4.798928,5.648312,4.350416,4.451770,4.451770e+00,14.239382,9.787612,0.0,...,0.0,10.253148,4.350416,4.451770,4.451770,27.077592,22.625822,0.0,22.625822,0.0
3,lgb_base,1.0,5.980217,5.648312,4.451770,7.910317,7.910317e+00,21.149699,13.239382,0.0,...,0.0,10.253148,4.451770,7.910317,7.910317,33.987908,26.077592,0.0,26.077592,0.0
4,lgb_base,9.0,5.048564,5.648312,7.910317,1.017425,1.017425e+00,13.167124,12.149699,0.0,...,0.0,10.253148,7.910317,1.017425,1.017425,26.005333,24.987908,0.0,24.987908,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9561659,ets_mint,0.0,0.031334,0.458688,0.000000,0.000000,2.220446e-16,0.532890,0.532890,0.0,...,0.0,0.832637,0.000000,0.000000,0.000000,0.906839,0.906839,0.0,0.906839,0.0
9561660,ets_mint,0.0,0.068989,0.458688,0.000000,0.000000,2.220446e-16,0.532890,0.532890,0.0,...,0.0,0.832637,0.000000,0.000000,0.000000,0.906839,0.906839,0.0,0.906839,0.0
9561661,ets_mint,0.0,0.095974,0.458688,0.000000,0.021772,2.177229e-02,0.554662,0.532890,0.0,...,0.0,0.832637,0.000000,0.021772,0.021772,0.928612,0.906839,0.0,0.906839,0.0
9561662,ets_mint,0.0,0.121862,0.458688,0.021772,0.025888,2.588752e-02,0.580550,0.554662,0.0,...,0.0,0.832637,0.021772,0.025888,0.025888,0.954499,0.928612,0.0,0.928612,0.0
9561663,ets_mint,0.0,0.114249,0.458688,0.025888,0.000000,2.220446e-16,0.580550,0.580550,0.0,...,0.0,0.832637,0.025888,0.000000,0.000000,0.954499,0.954499,0.0,0.954499,0.0

### orders_collector

In [5]:
from tqdm import tqdm
dff = {}
df = base[['name','true_demand', 'forecasts']]
for tsl in tqdm(['90', '95', '99']):
    df[f'ot_{tsl}'] = base[f'ot_{tsl}']
    df[f'ot_bu{tsl}'] = bu[f'ot_{tsl}']
    df[f'ot_tdfp{tsl}'] = tdfp[f'ot_{tsl}']
    df[f'ot_mint{tsl}'] = mint[f'ot_{tsl}']
    #dff[f'{tsl}'] = df
    #df.to_pickle(f"{tsl}_bullwhip_cv.pkl")

  0%|                                                                                            | 0/3 [00:00<?, ?it/s]C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_{tsl}'] = base[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_bu{tsl}'] = bu[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_tdfp{tsl}'] = tdfp[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_mint{tsl}'] = mint[f'ot_{tsl}']
 33%|████████████████████████████                                                        | 1/3 [00:00<00:00,  9.56it/s]C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_{tsl}'] = base[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_bu{tsl}'] = bu[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_tdfp{tsl}'] = tdfp[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_mint{tsl}'] = mint[f'ot_{tsl}']
 67%|████████████████████████████████████████████████████████                            | 2/3 [00:00<00:00,  9.51it/s]C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_{tsl}'] = base[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_bu{tsl}'] = bu[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_tdfp{tsl}'] = tdfp[f'ot_{tsl}']
C:\Users\qifei\AppData\Local\Temp\ipykernel_43860\4222763729.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[f'ot_mint{tsl}'] = mint[f'ot_{tsl}']
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  9.78it/s]

In [6]:
df.to_pickle("all_order.pkl")
df

,name,true_demand,forecasts,ot_90,ot_bu90,ot_tdfp90,ot_mint90,ot_95,ot_bu95,ot_tdfp95,ot_mint95,ot_99,ot_bu99,ot_tdfp99,ot_mint99
0,lgb_base,4.0,5.689794,5.648312,15.747402,5.648312,10.467349,7.249530,20.211572,7.249530,13.434492,10.253148,28.585611,10.253148,18.999925
1,lgb_base,5.0,4.679130,2.989336,4.350416,2.989336,3.557998,2.989336,4.350416,2.989336,3.557964,2.989336,4.350416,2.989336,3.557878
2,lgb_base,7.0,4.798928,5.119798,4.451770,5.119798,4.807548,5.119798,4.451770,5.119798,4.807558,5.119798,4.451770,5.119798,4.807583
3,lgb_base,1.0,5.980217,8.181289,7.910317,8.181289,7.931240,8.181289,7.910317,8.181289,7.931244,8.181289,7.910317,8.181289,7.931255
4,lgb_base,9.0,5.048564,0.068346,1.017425,0.068346,0.783484,0.068346,1.017425,0.068346,0.783501,0.068346,1.017425,0.068346,0.783545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9561659,ets_mint,0.0,0.031334,0.000000,0.000000,0.000000,0.022128,0.000000,0.000000,0.000000,0.022130,0.000000,0.000000,0.000000,0.022135
9561660,ets_mint,0.0,0.068989,0.000000,0.000000,0.016562,0.013579,0.000000,0.000000,0.016562,0.013581,0.000000,0.000000,0.016562,0.013587
9561661,ets_mint,0.0,0.095974,0.021772,0.021772,0.028005,0.025355,0.021772,0.021772,0.028005,0.025356,0.021772,0.021772,0.028005,0.025357
9561662,ets_mint,0.0,0.121862,0.025888,0.025888,0.025936,0.026458,0.025888,0.025888,0.025936,0.026458,0.025888,0.025888,0.025936,0.026459
9561663,ets_mint,0.0,0.114249,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

### products_list

In [7]:
prdd = pd.DataFrame({'products':list(tag['total/cat_id/dept_id/item_id'])})['products'].str.split('/')
prd  =  [i[-1] for i in prdd]
prd_idx = pd.DataFrame({f'{i}': uid[uid['unique_id'].str.contains(f'{i}')].index.tolist() for i in tqdm(prd)})
prd_idx.to_pickle("prd_idx.pkl")
prd_idx

  1%|▋                                                                               | 26/3049 [00:11<22:48,  2.21it/s]

KeyboardInterrupt:

### CV and Bullwhip Effect Ratio

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm

In [2]:
path = 'E:/yjz/Extension for hts/JayCode/Models/'

orders = pd.read_pickle(f"all_order.pkl")#.drop(columns = 'forecasts')
uid    = pd.read_pickle(f"{path}721future_28.pkl")[['unique_id','ds']]
prd_idx= pd.read_pickle(f"prd_idx.pkl")
# ao = pd.read_pickle("actual_order.pkl")

In [3]:
prd_idx

,FOODS_1_001,FOODS_1_002,FOODS_1_003,FOODS_1_004,FOODS_1_005,FOODS_1_006,FOODS_1_008,FOODS_1_009,FOODS_1_010,FOODS_1_011,...,HOUSEHOLD_2_507,HOUSEHOLD_2_508,HOUSEHOLD_2_509,HOUSEHOLD_2_510,HOUSEHOLD_2_511,HOUSEHOLD_2_512,HOUSEHOLD_2_513,HOUSEHOLD_2_514,HOUSEHOLD_2_515,HOUSEHOLD_2_516
0,0,28,56,84,112,140,168,196,224,252,...,85092,85120,85148,85176,85204,85232,85260,85288,85316,85344
1,1,29,57,85,113,141,169,197,225,253,...,85093,85121,85149,85177,85205,85233,85261,85289,85317,85345
2,2,30,58,86,114,142,170,198,226,254,...,85094,85122,85150,85178,85206,85234,85262,85290,85318,85346
3,3,31,59,87,115,143,171,199,227,255,...,85095,85123,85151,85179,85207,85235,85263,85291,85319,85347
4,4,32,60,88,116,144,172,200,228,256,...,85096,85124,85152,85180,85208,85236,85264,85292,85320,85348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,1109859,1109887,1109915,1109943,1109971,1109999,1110027,1110055,1110083,1110111,...,1194951,1194979,1195007,1195035,1195063,1195091,1195119,1195147,1195175,1195203
388,1109860,1109888,1109916,1109944,1109972,1110000,1110028,1110056,1110084,1110112,...,1194952,1194980,1195008,1195036,1195064,1195092,1195120,1195148,1195176,1195204
389,1109861,1109889,1109917,1109945,1109973,1110001,1110029,1110057,1110085,1110113,...,1194953,1194981,1195009,1195037,1195065,1195093,1195121,1195149,1195177,1195205
390,1109862,1109890,1109918,1109946,1109974,1110002,1110030,1110058,1110086,1110114,...,1194954,1194982,1195010,1195038,1195066,1195094,1195122,1195150,1195178,1195206
391,1109863,1109891,1109919,1109947,1109975,1110003,1110031,1110059,1110087,1110115,...,1194955,1194983,1195011,1195039,1195067,1195095,1195123,1195151,1195179,1195207

In [4]:
orders

,name,true_demand,forecasts,ot_90,ot_bu90,ot_tdfp90,ot_mint90,ot_95,ot_bu95,ot_tdfp95,ot_mint95,ot_99,ot_bu99,ot_tdfp99,ot_mint99
0,lgb_base,4.0,5.689794,5.648312,15.747402,5.648312,10.467349,7.249530,20.211572,7.249530,13.434492,10.253148,28.585611,10.253148,18.999925
1,lgb_base,5.0,4.679130,2.989336,4.350416,2.989336,3.557998,2.989336,4.350416,2.989336,3.557964,2.989336,4.350416,2.989336,3.557878
2,lgb_base,7.0,4.798928,5.119798,4.451770,5.119798,4.807548,5.119798,4.451770,5.119798,4.807558,5.119798,4.451770,5.119798,4.807583
3,lgb_base,1.0,5.980217,8.181289,7.910317,8.181289,7.931240,8.181289,7.910317,8.181289,7.931244,8.181289,7.910317,8.181289,7.931255
4,lgb_base,9.0,5.048564,0.068346,1.017425,0.068346,0.783484,0.068346,1.017425,0.068346,0.783501,0.068346,1.017425,0.068346,0.783545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9561659,ets_mint,0.0,0.031334,0.000000,0.000000,0.000000,0.022128,0.000000,0.000000,0.000000,0.022130,0.000000,0.000000,0.000000,0.022135
9561660,ets_mint,0.0,0.068989,0.000000,0.000000,0.016562,0.013579,0.000000,0.000000,0.016562,0.013581,0.000000,0.000000,0.016562,0.013587
9561661,ets_mint,0.0,0.095974,0.021772,0.021772,0.028005,0.025355,0.021772,0.021772,0.028005,0.025356,0.021772,0.021772,0.028005,0.025357
9561662,ets_mint,0.0,0.121862,0.025888,0.025888,0.025936,0.026458,0.025888,0.025888,0.025936,0.026458,0.025888,0.025888,0.025936,0.026459
9561663,ets_mint,0.0,0.114249,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [5]:
%%time
lst = orders['name'].unique().tolist()
df  = orders.copy()
frdr_ = pd.concat([pd.concat([uid,  df[df['name'] == i].reset_index(drop = True)], axis = 1)for i in tqdm(lst)])#.reset_index()# ao,

dff = frdr_.copy()
split_cols = dff['unique_id'].str.split('/', expand=False)

dff['product'] = pd.DataFrame([ i[-1] for  i in tqdm(split_cols)]) 
dff['level'] = pd.DataFrame([len(i) - 3 for i in tqdm(split_cols)])

100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:06<00:00,  1.25it/s]
100%|███████████████████████████████████████████████████████████████████| 9561664/9561664 [00:03<00:00, 2562748.33it/s]
100%|███████████████████████████████████████████████████████████████████| 9561664/9561664 [00:04<00:00, 2041424.51it/s]

CPU times: total: 44.8 s
Wall time: 44.7 s

In [6]:
dff

,unique_id,ds,name,true_demand,forecasts,ot_90,ot_bu90,ot_tdfp90,ot_mint90,ot_95,ot_bu95,ot_tdfp95,ot_mint95,ot_99,ot_bu99,ot_tdfp99,ot_mint99,product,level
0,TOTAL/FOODS/FOODS_1/FOODS_1_001,1914,lgb_base,4.0,5.689794,5.648312,15.747402,5.648312,10.467349,7.249530,20.211572,7.249530,13.434492,10.253148,28.585611,10.253148,18.999925,FOODS_1_001,1
1,TOTAL/FOODS/FOODS_1/FOODS_1_001,1915,lgb_base,5.0,4.679130,2.989336,4.350416,2.989336,3.557998,2.989336,4.350416,2.989336,3.557964,2.989336,4.350416,2.989336,3.557878,FOODS_1_001,1
2,TOTAL/FOODS/FOODS_1/FOODS_1_001,1916,lgb_base,7.0,4.798928,5.119798,4.451770,5.119798,4.807548,5.119798,4.451770,5.119798,4.807558,5.119798,4.451770,5.119798,4.807583,FOODS_1_001,1
3,TOTAL/FOODS/FOODS_1/FOODS_1_001,1917,lgb_base,1.0,5.980217,8.181289,7.910317,8.181289,7.931240,8.181289,7.910317,8.181289,7.931244,8.181289,7.910317,8.181289,7.931255,FOODS_1_001,1
4,TOTAL/FOODS/FOODS_1/FOODS_1_001,1918,lgb_base,9.0,5.048564,0.068346,1.017425,0.068346,0.783484,0.068346,1.017425,0.068346,0.783501,0.068346,1.017425,0.068346,0.783545,FOODS_1_001,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195203,TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_...,1937,ets_mint,0.0,0.031334,0.000000,0.000000,0.000000,0.022128,0.000000,0.000000,0.000000,0.022130,0.000000,0.000000,0.000000,0.022135,HOUSEHOLD_2_516,3
1195204,TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_...,1938,ets_mint,0.0,0.068989,0.000000,0.000000,0.016562,0.013579,0.000000,0.000000,0.016562,0.013581,0.000000,0.000000,0.016562,0.013587,HOUSEHOLD_2_516,3
1195205,TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_...,1939,ets_mint,0.0,0.095974,0.021772,0.021772,0.028005,0.025355,0.021772,0.021772,0.028005,0.025356,0.021772,0.021772,0.028005,0.025357,HOUSEHOLD_2_516,3
1195206,TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_...,1940,ets_mint,0.0,0.121862,0.025888,0.025888,0.025936,0.026458,0.025888,0.025888,0.025936,0.026458,0.025888,0.025888,0.025936,0.026459,HOUSEHOLD_2_516,3
1195207,TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_...,1941,ets_mint,0.0,0.114249,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,HOUSEHOLD_2_516,3

In [8]:
var_ = dff.groupby(['unique_id', 'name', 'product', 'level']).var()
lst2 = var_.columns.tolist()
var_[lst2[-13:]] = var_[lst2[-13:]].div(var_['true_demand'], axis=0)
# var_['forecasts'] = var_['forecasts'].div(var_['true_demand'], axis = 0)

In [9]:
var_

                                                                                          ds  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      67.666667
                                                   ets_bu   FOODS_1_001     3      67.666667
                                                   ets_mint FOODS_1_001     3      67.666667
                                                   ets_td   FOODS_1_001     3      67.666667
                                                   lgb_base FOODS_1_001     3      67.666667
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      67.666667
                                                   lgb_base HOUSEHOLD_2_516 3      67.666667
                                                   lgb_bu   HOUSEHOLD_2_516 3      67.666667
                                                   lgb_mint HOUSEHOLD_2_516 3      67.666667
                                                   lgb_td   HOUSEHOLD_2_516 3      67.666667

                                                                                   true_demand  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3         1.929894
                                                   ets_bu   FOODS_1_001     3         1.929894
                                                   ets_mint FOODS_1_001     3         1.929894
                                                   ets_td   FOODS_1_001     3         1.929894
                                                   lgb_base FOODS_1_001     3         1.929894
...                                                                                        ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3         0.068783
                                                   lgb_base HOUSEHOLD_2_516 3         0.068783
                                                   lgb_bu   HOUSEHOLD_2_516 3         0.068783
                                                   lgb_mint HOUSEHOLD_2_516 3         0.068783
                                                   lgb_td   HOUSEHOLD_2_516 3         0.068783

                                                                                   forecasts  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       0.002257
                                                   ets_bu   FOODS_1_001     3       0.002257
                                                   ets_mint FOODS_1_001     3       0.006027
                                                   ets_td   FOODS_1_001     3       0.003945
                                                   lgb_base FOODS_1_001     3       0.082218
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       0.000730
                                                   lgb_base HOUSEHOLD_2_516 3       0.142636
                                                   lgb_bu   HOUSEHOLD_2_516 3       0.142636
                                                   lgb_mint HOUSEHOLD_2_516 3       0.112427
                                                   lgb_td   HOUSEHOLD_2_516 3       0.070241

                                                                                      ot_90  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      1.034852
                                                   ets_bu   FOODS_1_001     3      1.034852
                                                   ets_mint FOODS_1_001     3      1.020277
                                                   ets_td   FOODS_1_001     3      1.031719
                                                   lgb_base FOODS_1_001     3      1.269884
...                                                                                     ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      1.085507
                                                   lgb_base HOUSEHOLD_2_516 3      1.460371
                                                   lgb_bu   HOUSEHOLD_2_516 3      1.460371
                                                   lgb_mint HOUSEHOLD_2_516 3      1.417201
                                                   lgb_td   HOUSEHOLD_2_516 3      1.304328

                                                                                    ot_bu90  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      1.034852
                                                   ets_bu   FOODS_1_001     3      1.034852
                                                   ets_mint FOODS_1_001     3      1.020277
                                                   ets_td   FOODS_1_001     3      1.031719
                                                   lgb_base FOODS_1_001     3      1.269884
...                                                                                     ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      1.085507
                                                   lgb_base HOUSEHOLD_2_516 3      1.460371
                                                   lgb_bu   HOUSEHOLD_2_516 3      1.460371
                                                   lgb_mint HOUSEHOLD_2_516 3      1.417201
                                                   lgb_td   HOUSEHOLD_2_516 3      1.304328

                                                                                   ot_tdfp90  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       1.067289
                                                   ets_bu   FOODS_1_001     3       1.028848
                                                   ets_mint FOODS_1_001     3       1.146937
                                                   ets_td   FOODS_1_001     3       1.065806
                                                   lgb_base FOODS_1_001     3       1.500536
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       1.023531
                                                   lgb_base HOUSEHOLD_2_516 3       1.857943
                                                   lgb_bu   HOUSEHOLD_2_516 3       1.916730
                                                   lgb_mint HOUSEHOLD_2_516 3       1.780745
                                                   lgb_td   HOUSEHOLD_2_516 3       1.720992

                                                                                   ot_mint90  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       1.028442
                                                   ets_bu   FOODS_1_001     3       1.027066
                                                   ets_mint FOODS_1_001     3       1.018308
                                                   ets_td   FOODS_1_001     3       1.025707
                                                   lgb_base FOODS_1_001     3       1.268725
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       1.030316
                                                   lgb_base HOUSEHOLD_2_516 3       1.451901
                                                   lgb_bu   HOUSEHOLD_2_516 3       1.450498
                                                   lgb_mint HOUSEHOLD_2_516 3       1.369814
                                                   lgb_td   HOUSEHOLD_2_516 3       1.286418

                                                                                      ot_95  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      1.050723
                                                   ets_bu   FOODS_1_001     3      1.050723
                                                   ets_mint FOODS_1_001     3      1.034079
                                                   ets_td   FOODS_1_001     3      1.047683
                                                   lgb_base FOODS_1_001     3      1.287514
...                                                                                     ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      1.151815
                                                   lgb_base HOUSEHOLD_2_516 3      1.536979
                                                   lgb_bu   HOUSEHOLD_2_516 3      1.536979
                                                   lgb_mint HOUSEHOLD_2_516 3      1.489271
                                                   lgb_td   HOUSEHOLD_2_516 3      1.381550

                                                                                    ot_bu95  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      1.050723
                                                   ets_bu   FOODS_1_001     3      1.050723
                                                   ets_mint FOODS_1_001     3      1.034079
                                                   ets_td   FOODS_1_001     3      1.047683
                                                   lgb_base FOODS_1_001     3      1.287514
...                                                                                     ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      1.151815
                                                   lgb_base HOUSEHOLD_2_516 3      1.536979
                                                   lgb_bu   HOUSEHOLD_2_516 3      1.536979
                                                   lgb_mint HOUSEHOLD_2_516 3      1.489271
                                                   lgb_td   HOUSEHOLD_2_516 3      1.381550

                                                                                   ot_tdfp95  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       1.066044
                                                   ets_bu   FOODS_1_001     3       1.027687
                                                   ets_mint FOODS_1_001     3       1.145470
                                                   ets_td   FOODS_1_001     3       1.064560
                                                   lgb_base FOODS_1_001     3       1.499229
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       1.029988
                                                   lgb_base HOUSEHOLD_2_516 3       1.864609
                                                   lgb_bu   HOUSEHOLD_2_516 3       1.924647
                                                   lgb_mint HOUSEHOLD_2_516 3       1.786431
                                                   lgb_td   HOUSEHOLD_2_516 3       1.727779

                                                                                   ot_mint95  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       1.036385
                                                   ets_bu   FOODS_1_001     3       1.035001
                                                   ets_mint FOODS_1_001     3       1.024888
                                                   ets_td   FOODS_1_001     3       1.033712
                                                   lgb_base FOODS_1_001     3       1.278355
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       1.056807
                                                   lgb_base HOUSEHOLD_2_516 3       1.482091
                                                   lgb_bu   HOUSEHOLD_2_516 3       1.481996
                                                   lgb_mint HOUSEHOLD_2_516 3       1.397636
                                                   lgb_td   HOUSEHOLD_2_516 3       1.317158

                                                                                      ot_99  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      1.100562
                                                   ets_bu   FOODS_1_001     3      1.100562
                                                   ets_mint FOODS_1_001     3      1.078206
                                                   ets_td   FOODS_1_001     3      1.097694
                                                   lgb_base FOODS_1_001     3      1.342284
...                                                                                     ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      1.327667
                                                   lgb_base HOUSEHOLD_2_516 3      1.740818
                                                   lgb_bu   HOUSEHOLD_2_516 3      1.740818
                                                   lgb_mint HOUSEHOLD_2_516 3      1.681225
                                                   lgb_td   HOUSEHOLD_2_516 3      1.586541

                                                                                    ot_bu99  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3      1.100562
                                                   ets_bu   FOODS_1_001     3      1.100562
                                                   ets_mint FOODS_1_001     3      1.078206
                                                   ets_td   FOODS_1_001     3      1.097694
                                                   lgb_base FOODS_1_001     3      1.342284
...                                                                                     ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3      1.327667
                                                   lgb_base HOUSEHOLD_2_516 3      1.740818
                                                   lgb_bu   HOUSEHOLD_2_516 3      1.740818
                                                   lgb_mint HOUSEHOLD_2_516 3      1.681225
                                                   lgb_td   HOUSEHOLD_2_516 3      1.586541

                                                                                   ot_tdfp99  \
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       1.066283
                                                   ets_bu   FOODS_1_001     3       1.028204
                                                   ets_mint FOODS_1_001     3       1.144956
                                                   ets_td   FOODS_1_001     3       1.064796
                                                   lgb_base FOODS_1_001     3       1.499337
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       1.049033
                                                   lgb_base HOUSEHOLD_2_516 3       1.885370
                                                   lgb_bu   HOUSEHOLD_2_516 3       1.949105
                                                   lgb_mint HOUSEHOLD_2_516 3       1.804413
                                                   lgb_td   HOUSEHOLD_2_516 3       1.748765

                                                                                   ot_mint99
unique_id                                          name     product         level
TOTAL/CA/CA_1/FOODS/FOODS_1/FOODS_1_001            ets_base FOODS_1_001     3       1.064139
                                                   ets_bu   FOODS_1_001     3       1.062739
                                                   ets_mint FOODS_1_001     3       1.048793
                                                   ets_td   FOODS_1_001     3       1.061583
                                                   lgb_base FOODS_1_001     3       1.310962
...                                                                                      ...
TOTAL/WI/WI_3/HOUSEHOLD/HOUSEHOLD_2/HOUSEHOLD_2... ets_td   HOUSEHOLD_2_516 3       1.128880
                                                   lgb_base HOUSEHOLD_2_516 3       1.565347
                                                   lgb_bu   HOUSEHOLD_2_516 3       1.568788
                                                   lgb_mint HOUSEHOLD_2_516 3       1.474372
                                                   lgb_td   HOUSEHOLD_2_516 3       1.401442

[341488 rows x 15 columns]

In [10]:
### .xs('FOODS_1_001', level='product')
df2 = var_[np.isfinite(var_).all(axis=1)] # dropna and inf value
uids = df2.index.get_level_values('unique_id').unique()#.tolist()
#uids.str.split('/').str[-1].tolist()
vlist = []
for i in tqdm(uids.str.split('/').str[-1].tolist()):
    df = df2.xs(f'{i}', level='product').groupby(['level', 'name']).mean()#['level', 'product', 'name']
    vlist.append(df)

100%|███████████████████████████████████████████████████████████████████████████| 41803/41803 [02:06<00:00, 330.09it/s]

In [16]:
pd.concat(vlist).groupby(['level', 'name']).median().iloc[:,3:].to_csv("bwe.csv")

In [17]:
pd.concat(vlist).groupby(['level', 'name']).median().iloc[:,3:] # volatility

                   ot_90   ot_bu90  ot_tdfp90  ot_mint90     ot_95   ot_bu95  \
level name
1     ets_base  1.215392  1.103374   1.215392   1.113103  1.198767  1.193440
      ets_bu    1.094923  1.103374   1.094923   1.066986  1.083705  1.193440
      ets_mint  1.151968  1.120057   1.151968   1.098347  1.135799  1.195362
      ets_td    1.215392  1.184951   1.215392   1.154897  1.198767  1.289545
      lgb_base  1.559166  1.333304   1.559166   1.373464  1.545223  1.430158
      lgb_bu    1.473702  1.333304   1.473702   1.343280  1.460540  1.430158
      lgb_mint  1.497469  1.343570   1.497469   1.355083  1.481283  1.441865
      lgb_td    1.559166  1.389563   1.559166   1.409712  1.545223  1.503093
2     ets_base  1.077120  1.061637   1.112473   1.061964  1.087041  1.112973
      ets_bu    1.043043  1.061637   1.047111   1.038810  1.053932  1.112973
      ets_mint  1.063188  1.059674   1.073943   1.047723  1.068101  1.106653
      ets_td    1.096932  1.101603   1.107959   1.084433  1.107459  1.159449
      lgb_base  1.385206  1.288819   1.443370   1.310812  1.394313  1.344147
      lgb_bu    1.356848  1.288819   1.388454   1.295222  1.364319  1.344147
      lgb_mint  1.362413  1.292352   1.399807   1.301027  1.369092  1.347488
      lgb_td    1.401179  1.316793   1.437847   1.330751  1.413402  1.378370
3     ets_base  1.028244  1.028244   1.028358   1.018412  1.053007  1.053007
      ets_bu    1.028244  1.028244   1.003997   1.013367  1.053007  1.053007
      ets_mint  1.011778  1.011778   1.003543   1.000378  1.035878  1.035878
      ets_td    1.038995  1.038995   1.023033   1.024607  1.065916  1.065916
      lgb_base  1.247474  1.247474   1.267134   1.227001  1.277147  1.277147
      lgb_bu    1.247474  1.247474   1.253560   1.224009  1.277147  1.277147
      lgb_mint  1.243411  1.243411   1.246220   1.221122  1.272468  1.272468
      lgb_td    1.240372  1.240372   1.259651   1.218824  1.271638  1.271638

                ot_tdfp95  ot_mint95     ot_99   ot_bu99  ot_tdfp99  ot_mint99
level name
1     ets_base   1.198767   1.142286  1.197593  1.497649   1.197593   1.241277
      ets_bu     1.083705   1.094349  1.087641  1.497649   1.087641   1.185144
      ets_mint   1.135799   1.116454  1.129697  1.452483   1.129697   1.199201
      ets_td     1.198767   1.185115  1.197593  1.615163   1.197593   1.299155
      lgb_base   1.545223   1.398871  1.540906  1.745586   1.540906   1.504911
      lgb_bu     1.460540   1.370596  1.456016  1.745586   1.456016   1.473621
      lgb_mint   1.481283   1.380920  1.471487  1.733243   1.471487   1.482649
      lgb_td     1.545223   1.441010  1.540906  1.824163   1.540906   1.556604
2     ets_base   1.109205   1.079995  1.128978  1.267243   1.113071   1.141145
      ets_bu     1.044033   1.057032  1.095945  1.267243   1.049950   1.115538
      ets_mint   1.068499   1.060488  1.101113  1.242781   1.069933   1.110148
      ets_td     1.104367   1.101782  1.150112  1.322418   1.108275   1.166838
      lgb_base   1.439526   1.328686  1.434282  1.506185   1.438880   1.393735
      lgb_bu     1.383950   1.312720  1.401828  1.506185   1.385093   1.373975
      lgb_mint   1.395692   1.317876  1.404890  1.505751   1.394400   1.378087
      lgb_td     1.435147   1.351709  1.454744  1.554405   1.434318   1.421487
3     ets_base   1.028968   1.028448  1.125451  1.125451   1.033688   1.060453
      ets_bu     1.004489   1.023204  1.125451  1.125451   1.009534   1.054256
      ets_mint   1.003417   1.007397  1.098967  1.098967   1.006231   1.034715
      ets_td     1.023320   1.034903  1.140651  1.140651   1.027763   1.067800
      lgb_base   1.266586   1.238985  1.355631  1.355631   1.271295   1.276523
      lgb_bu     1.253782   1.236765  1.355631  1.355631   1.259497   1.270998
      lgb_mint   1.245819   1.232490  1.348654  1.348654   1.249773   1.266768
      lgb_td     1.259466   1.231594  1.357386  1.357386   1.262464   1.271613

## Mean bullwhip summary

In [ ]:
bullwhip_mean_summary = (
    pd.concat(vlist)
    .groupby(['level', 'name'])
    .mean()
    .iloc[:, 3:]
    .reset_index()
)
bullwhip_mean_summary