## TDFP

Top-down forecast-proportions **order reconciliation** using the cleaned simulation pipeline.

In [1]:
path1 = 'E:/yjz/Extension for hts/JayCode/Models/'

import warnings
warnings.simplefilter("ignore")

import numpy as np
import pandas as pd
from tqdm import tqdm
from hierarchicalforecast.core import HierarchicalReconciliation
from hierarchicalforecast.methods import TopDown

from inventory_pipeline import save_pickle, run_fixed_loop
#from inventory_pipeline import dual_save, run_fixed_loop

In [2]:
lead_time = 1
MODEL_NAMES = ['lgb_base', 'lgb_bu', 'lgb_td', 'lgb_mint',
               'ets_base', 'ets_bu', 'ets_td', 'ets_mint']
on = ['ot_90', 'ot_95', 'ot_99']

lp = {"l10": (0, 3049), "l11": (3049, 3049 + 9147), "l12": (3049 + 9147, 3049 + 9147 + 30490)}
lvls = []
for k, (a, b) in lp.items():
    lvls.append([k[1:]] * 28 * (b - a))
levels = pd.concat([pd.DataFrame({'levels': lvls[i]}) for i in range(len(lvls))], ignore_index=True)

test = pd.read_pickle(f"{path1}721future_28.pkl").reset_index(drop=True)
truth = test['y'].reset_index(drop=True)
S = pd.read_pickle(f"{path1}721S_df.pkl")
tags = pd.read_pickle(f"{path1}tags.bin")

ts = pd.concat([levels, test[['unique_id', 'ds']].reset_index(drop=True)], axis=1)
ts2 = ts[ts['levels'].isin(['10', '11', '12'])].reset_index(drop=True)

s = S.copy()
l10_12 = [
    'total/cat_id/dept_id/item_id',
    'total/state_id/cat_id/dept_id/item_id',
    'total/state_id/store_id/cat_id/dept_id/item_id',
]
prods = [u.split('/')[-1] for u in tags[l10_12[0]]]

lgbs = pd.read_pickle(f"lgbInvtSim_L{lead_time}.pkl").reset_index(drop=True)
etss = pd.read_pickle(f"etsInvtSim_L{lead_time}.pkl").reset_index(drop=True)
base_all = pd.concat([lgbs, etss], ignore_index=True)

TDFP = HierarchicalReconciliation(reconcilers=[TopDown(method='forecast_proportions')])

In [3]:
prods

['FOODS_1_001',
 'FOODS_1_002',
 'FOODS_1_003',
 'FOODS_1_004',
 'FOODS_1_005',
 'FOODS_1_006',
 'FOODS_1_008',
 'FOODS_1_009',
 'FOODS_1_010',
 'FOODS_1_011',
 'FOODS_1_012',
 'FOODS_1_013',
 'FOODS_1_014',
 'FOODS_1_015',
 'FOODS_1_016',
 'FOODS_1_017',
 'FOODS_1_018',
 'FOODS_1_019',
 'FOODS_1_020',
 'FOODS_1_021',
 'FOODS_1_022',
 'FOODS_1_023',
 'FOODS_1_024',
 'FOODS_1_025',
 'FOODS_1_026',
 'FOODS_1_027',
 'FOODS_1_028',
 'FOODS_1_029',
 'FOODS_1_030',
 'FOODS_1_031',
 'FOODS_1_032',
 'FOODS_1_033',
 'FOODS_1_034',
 'FOODS_1_035',
 'FOODS_1_036',
 'FOODS_1_037',
 'FOODS_1_038',
 'FOODS_1_039',
 'FOODS_1_040',
 'FOODS_1_041',
 'FOODS_1_042',
 'FOODS_1_043',
 'FOODS_1_044',
 'FOODS_1_045',
 'FOODS_1_046',
 'FOODS_1_047',
 'FOODS_1_048',
 'FOODS_1_049',
 'FOODS_1_050',
 'FOODS_1_051',
 'FOODS_1_052',
 'FOODS_1_053',
 'FOODS_1_054',
 'FOODS_1_055',
 'FOODS_1_056',
 'FOODS_1_057',
 'FOODS_1_058',
 'FOODS_1_059',
 'FOODS_1_060',
 'FOODS_1_061',
 'FOODS_1_062',
 'FOODS_1_063',
 'FOODS_1_064',
 'FOODS_1_065',
 'FOODS_1_066',
 'FOODS_1_067',
 'FOODS_1_068',
 'FOODS_1_069',
 'FOODS_1_070',
 'FOODS_1_071',
 'FOODS_1_072',
 'FOODS_1_073',
 'FOODS_1_074',
 'FOODS_1_075',
 'FOODS_1_076',
 'FOODS_1_077',
 'FOODS_1_078',
 'FOODS_1_079',
 'FOODS_1_080',
 'FOODS_1_081',
 'FOODS_1_082',
 'FOODS_1_083',
 'FOODS_1_084',
 'FOODS_1_085',
 'FOODS_1_086',
 'FOODS_1_087',
 'FOODS_1_088',
 'FOODS_1_089',
 'FOODS_1_090',
 'FOODS_1_091',
 'FOODS_1_092',
 'FOODS_1_093',
 'FOODS_1_094',
 'FOODS_1_095',
 'FOODS_1_096',
 'FOODS_1_097',
 'FOODS_1_098',
 'FOODS_1_099',
 'FOODS_1_101',
 'FOODS_1_102',
 'FOODS_1_103',
 'FOODS_1_104',
 'FOODS_1_105',
 'FOODS_1_106',
 'FOODS_1_107',
 'FOODS_1_108',
 'FOODS_1_109',
 'FOODS_1_110',
 'FOODS_1_111',
 'FOODS_1_112',
 'FOODS_1_113',
 'FOODS_1_114',
 'FOODS_1_115',
 'FOODS_1_116',
 'FOODS_1_117',
 'FOODS_1_118',
 'FOODS_1_119',
 'FOODS_1_120',
 'FOODS_1_121',
 'FOODS_1_122',
 'FOODS_1_123',
 'FOODS_1_124',
 'FOODS_1_125',
 'FOODS_1_126',
 'FOODS_1_127',
 'FOODS_1_128',
 'FOODS_1_129',
 'FOODS_1_130',
 'FOODS_1_131',
 'FOODS_1_132',
 'FOODS_1_133',
 'FOODS_1_134',
 'FOODS_1_135',
 'FOODS_1_136',
 'FOODS_1_137',
 'FOODS_1_138',
 'FOODS_1_139',
 'FOODS_1_140',
 'FOODS_1_141',
 'FOODS_1_142',
 'FOODS_1_143',
 'FOODS_1_144',
 'FOODS_1_145',
 'FOODS_1_146',
 'FOODS_1_147',
 'FOODS_1_148',
 'FOODS_1_149',
 'FOODS_1_150',
 'FOODS_1_151',
 'FOODS_1_152',
 'FOODS_1_153',
 'FOODS_1_154',
 'FOODS_1_155',
 'FOODS_1_156',
 'FOODS_1_157',
 'FOODS_1_158',
 'FOODS_1_159',
 'FOODS_1_160',
 'FOODS_1_161',
 'FOODS_1_162',
 'FOODS_1_163',
 'FOODS_1_164',
 'FOODS_1_166',
 'FOODS_1_167',
 'FOODS_1_168',
 'FOODS_1_169',
 'FOODS_1_170',
 'FOODS_1_171',
 'FOODS_1_172',
 'FOODS_1_173',
 'FOODS_1_174',
 'FOODS_1_175',
 'FOODS_1_176',
 'FOODS_1_177',
 'FOODS_1_178',
 'FOODS_1_179',
 'FOODS_1_180',
 'FOODS_1_181',
 'FOODS_1_182',
 'FOODS_1_183',
 'FOODS_1_184',
 'FOODS_1_185',
 'FOODS_1_186',
 'FOODS_1_187',
 'FOODS_1_188',
 'FOODS_1_189',
 'FOODS_1_190',
 'FOODS_1_191',
 'FOODS_1_192',
 'FOODS_1_193',
 'FOODS_1_194',
 'FOODS_1_195',
 'FOODS_1_196',
 'FOODS_1_197',
 'FOODS_1_198',
 'FOODS_1_199',
 'FOODS_1_200',
 'FOODS_1_201',
 'FOODS_1_202',
 'FOODS_1_203',
 'FOODS_1_204',
 'FOODS_1_205',
 'FOODS_1_206',
 'FOODS_1_207',
 'FOODS_1_208',
 'FOODS_1_209',
 'FOODS_1_210',
 'FOODS_1_211',
 'FOODS_1_212',
 'FOODS_1_213',
 'FOODS_1_214',
 'FOODS_1_215',
 'FOODS_1_216',
 'FOODS_1_217',
 'FOODS_1_218',
 'FOODS_1_219',
 'FOODS_2_001',
 'FOODS_2_002',
 'FOODS_2_003',
 'FOODS_2_004',
 'FOODS_2_005',
 'FOODS_2_006',
 'FOODS_2_007',
 'FOODS_2_008',
 'FOODS_2_009',
 'FOODS_2_010',
 'FOODS_2_011',
 'FOODS_2_012',
 'FOODS_2_013',
 'FOODS_2_014',
 'FOODS_2_015',
 'FOODS_2_016',
 'FOODS_2_017',
 'FOODS_2_018',
 'FOODS_2_019',
 'FOODS_2_020',
 'FOODS_2_021',
 'FOODS_2_022',
 'FOODS_2_023',
 'FOODS_2_024',
 'FOODS_2_025',
 'FOODS_2_026',
 'FOODS_2_027',
 'FOODS_2_028',
 'FOODS_2_029',
 'FOODS_2_030',
 'FOODS_2_031',
 'FOODS_2_032',
 'FOODS_2_033',
 'FOODS_2_034',
 'FOODS_2_035',
 'FOODS_2_036',
 'FOODS_2_037',
 'FOODS_2_038',
 'FOODS_2_039',
 'FOODS_2_040',
 'FOODS_2_041',
 'FOODS_2_042',
 'FOODS_2_043',
 'FOODS_2_044',
 'FOODS_2_045',
 'FOODS_2_046',
 'FOODS_2_047',
 'FOODS_2_048',
 'FOODS_2_049',
 'FOODS_2_050',
 'FOODS_2_051',
 'FOODS_2_052',
 'FOODS_2_053',
 'FOODS_2_054',
 'FOODS_2_055',
 'FOODS_2_056',
 'FOODS_2_057',
 'FOODS_2_058',
 'FOODS_2_059',
 'FOODS_2_060',
 'FOODS_2_061',
 'FOODS_2_062',
 'FOODS_2_063',
 'FOODS_2_064',
 'FOODS_2_065',
 'FOODS_2_066',
 'FOODS_2_067',
 'FOODS_2_068',
 'FOODS_2_069',
 'FOODS_2_070',
 'FOODS_2_071',
 'FOODS_2_072',
 'FOODS_2_073',
 'FOODS_2_074',
 'FOODS_2_075',
 'FOODS_2_076',
 'FOODS_2_077',
 'FOODS_2_078',
 'FOODS_2_079',
 'FOODS_2_080',
 'FOODS_2_081',
 'FOODS_2_082',
 'FOODS_2_083',
 'FOODS_2_084',
 'FOODS_2_085',
 'FOODS_2_086',
 'FOODS_2_087',
 'FOODS_2_088',
 'FOODS_2_089',
 'FOODS_2_090',
 'FOODS_2_091',
 'FOODS_2_092',
 'FOODS_2_093',
 'FOODS_2_094',
 'FOODS_2_095',
 'FOODS_2_096',
 'FOODS_2_097',
 'FOODS_2_099',
 'FOODS_2_100',
 'FOODS_2_101',
 'FOODS_2_102',
 'FOODS_2_103',
 'FOODS_2_104',
 'FOODS_2_105',
 'FOODS_2_106',
 'FOODS_2_107',
 'FOODS_2_108',
 'FOODS_2_109',
 'FOODS_2_110',
 'FOODS_2_111',
 'FOODS_2_112',
 'FOODS_2_113',
 'FOODS_2_114',
 'FOODS_2_115',
 'FOODS_2_116',
 'FOODS_2_117',
 'FOODS_2_118',
 'FOODS_2_119',
 'FOODS_2_120',
 'FOODS_2_121',
 'FOODS_2_122',
 'FOODS_2_123',
 'FOODS_2_124',
 'FOODS_2_125',
 'FOODS_2_126',
 'FOODS_2_127',
 'FOODS_2_128',
 'FOODS_2_129',
 'FOODS_2_130',
 'FOODS_2_131',
 'FOODS_2_132',
 'FOODS_2_133',
 'FOODS_2_134',
 'FOODS_2_135',
 'FOODS_2_136',
 'FOODS_2_137',
 'FOODS_2_138',
 'FOODS_2_139',
 'FOODS_2_140',
 'FOODS_2_141',
 'FOODS_2_142',
 'FOODS_2_143',
 'FOODS_2_144',
 'FOODS_2_145',
 'FOODS_2_146',
 'FOODS_2_147',
 'FOODS_2_148',
 'FOODS_2_149',
 'FOODS_2_150',
 'FOODS_2_151',
 'FOODS_2_152',
 'FOODS_2_153',
 'FOODS_2_154',
 'FOODS_2_155',
 'FOODS_2_156',
 'FOODS_2_157',
 'FOODS_2_158',
 'FOODS_2_159',
 'FOODS_2_160',
 'FOODS_2_161',
 'FOODS_2_162',
 'FOODS_2_163',
 'FOODS_2_164',
 'FOODS_2_165',
 'FOODS_2_166',
 'FOODS_2_167',
 'FOODS_2_168',
 'FOODS_2_169',
 'FOODS_2_170',
 'FOODS_2_171',
 'FOODS_2_172',
 'FOODS_2_173',
 'FOODS_2_174',
 'FOODS_2_175',
 'FOODS_2_176',
 'FOODS_2_177',
 'FOODS_2_178',
 'FOODS_2_179',
 'FOODS_2_180',
 'FOODS_2_181',
 'FOODS_2_182',
 'FOODS_2_183',
 'FOODS_2_184',
 'FOODS_2_185',
 'FOODS_2_186',
 'FOODS_2_187',
 'FOODS_2_188',
 'FOODS_2_189',
 'FOODS_2_190',
 'FOODS_2_191',
 'FOODS_2_192',
 'FOODS_2_193',
 'FOODS_2_194',
 'FOODS_2_195',
 'FOODS_2_196',
 'FOODS_2_197',
 'FOODS_2_198',
 'FOODS_2_199',
 'FOODS_2_200',
 'FOODS_2_201',
 'FOODS_2_202',
 'FOODS_2_203',
 'FOODS_2_204',
 'FOODS_2_205',
 'FOODS_2_206',
 'FOODS_2_207',
 'FOODS_2_208',
 'FOODS_2_209',
 'FOODS_2_210',
 'FOODS_2_211',
 'FOODS_2_212',
 'FOODS_2_213',
 'FOODS_2_214',
 'FOODS_2_215',
 'FOODS_2_216',
 'FOODS_2_217',
 'FOODS_2_218',
 'FOODS_2_219',
 'FOODS_2_220',
 'FOODS_2_221',
 'FOODS_2_222',
 'FOODS_2_223',
 'FOODS_2_224',
 'FOODS_2_225',
 'FOODS_2_226',
 'FOODS_2_227',
 'FOODS_2_228',
 'FOODS_2_229',
 'FOODS_2_230',
 'FOODS_2_231',
 'FOODS_2_232',
 'FOODS_2_233',
 'FOODS_2_234',
 'FOODS_2_235',
 'FOODS_2_236',
 'FOODS_2_237',
 'FOODS_2_238',
 'FOODS_2_239',
 'FOODS_2_240',
 'FOODS_2_241',
 'FOODS_2_242',
 'FOODS_2_243',
 'FOODS_2_244',
 'FOODS_2_245',
 'FOODS_2_246',
 'FOODS_2_247',
 'FOODS_2_248',
 'FOODS_2_249',
 'FOODS_2_250',
 'FOODS_2_251',
 'FOODS_2_252',
 'FOODS_2_253',
 'FOODS_2_254',
 'FOODS_2_255',
 'FOODS_2_256',
 'FOODS_2_257',
 'FOODS_2_258',
 'FOODS_2_259',
 'FOODS_2_260',
 'FOODS_2_261',
 'FOODS_2_262',
 'FOODS_2_263',
 'FOODS_2_264',
 'FOODS_2_265',
 'FOODS_2_266',
 'FOODS_2_267',
 'FOODS_2_268',
 'FOODS_2_269',
 'FOODS_2_270',
 'FOODS_2_271',
 'FOODS_2_272',
 'FOODS_2_273',
 'FOODS_2_274',
 'FOODS_2_275',
 'FOODS_2_276',
 'FOODS_2_277',
 'FOODS_2_278',
 'FOODS_2_279',
 'FOODS_2_280',
 'FOODS_2_281',
 'FOODS_2_282',
 'FOODS_2_283',
 'FOODS_2_284',
 'FOODS_2_285',
 'FOODS_2_286',
 'FOODS_2_287',
 'FOODS_2_288',
 'FOODS_2_289',
 'FOODS_2_290',
 'FOODS_2_291',
 'FOODS_2_292',
 'FOODS_2_293',
 'FOODS_2_294',
 'FOODS_2_295',
 'FOODS_2_296',
 'FOODS_2_297',
 'FOODS_2_298',
 'FOODS_2_299',
 'FOODS_2_300',
 'FOODS_2_301',
 'FOODS_2_302',
 'FOODS_2_303',
 'FOODS_2_304',
 'FOODS_2_305',
 'FOODS_2_306',
 'FOODS_2_307',
 'FOODS_2_308',
 'FOODS_2_309',
 'FOODS_2_310',
 'FOODS_2_311',
 'FOODS_2_312',
 'FOODS_2_313',
 'FOODS_2_314',
 'FOODS_2_315',
 'FOODS_2_316',
 'FOODS_2_317',
 'FOODS_2_318',
 'FOODS_2_319',
 'FOODS_2_320',
 'FOODS_2_321',
 'FOODS_2_322',
 'FOODS_2_323',
 'FOODS_2_324',
 'FOODS_2_325',
 'FOODS_2_326',
 'FOODS_2_327',
 'FOODS_2_328',
 'FOODS_2_329',
 'FOODS_2_330',
 'FOODS_2_331',
 'FOODS_2_332',
 'FOODS_2_333',
 'FOODS_2_334',
 'FOODS_2_335',
 'FOODS_2_336',
 'FOODS_2_337',
 'FOODS_2_338',
 'FOODS_2_339',
 'FOODS_2_340',
 'FOODS_2_341',
 'FOODS_2_342',
 'FOODS_2_343',
 'FOODS_2_344',
 'FOODS_2_345',
 'FOODS_2_346',
 'FOODS_2_347',
 'FOODS_2_348',
 'FOODS_2_349',
 'FOODS_2_350',
 'FOODS_2_351',
 'FOODS_2_352',
 'FOODS_2_353',
 'FOODS_2_354',
 'FOODS_2_355',
 'FOODS_2_356',
 'FOODS_2_357',
 'FOODS_2_358',
 'FOODS_2_359',
 'FOODS_2_360',
 'FOODS_2_361',
 'FOODS_2_362',
 'FOODS_2_363',
 'FOODS_2_364',
 'FOODS_2_365',
 'FOODS_2_366',
 'FOODS_2_367',
 'FOODS_2_368',
 'FOODS_2_369',
 'FOODS_2_370',
 'FOODS_2_371',
 'FOODS_2_372',
 'FOODS_2_373',
 'FOODS_2_374',
 'FOODS_2_375',
 'FOODS_2_376',
 'FOODS_2_377',
 'FOODS_2_378',
 'FOODS_2_379',
 'FOODS_2_380',
 'FOODS_2_381',
 'FOODS_2_382',
 'FOODS_2_383',
 'FOODS_2_384',
 'FOODS_2_385',
 'FOODS_2_386',
 'FOODS_2_387',
 'FOODS_2_388',
 'FOODS_2_389',
 'FOODS_2_390',
 'FOODS_2_391',
 'FOODS_2_392',
 'FOODS_2_393',
 'FOODS_2_394',
 'FOODS_2_395',
 'FOODS_2_396',
 'FOODS_2_397',
 'FOODS_2_398',
 'FOODS_2_399',
 'FOODS_3_001',
 'FOODS_3_002',
 'FOODS_3_003',
 'FOODS_3_004',
 'FOODS_3_005',
 'FOODS_3_006',
 'FOODS_3_007',
 'FOODS_3_008',
 'FOODS_3_009',
 'FOODS_3_010',
 'FOODS_3_011',
 'FOODS_3_012',
 'FOODS_3_013',
 'FOODS_3_014',
 'FOODS_3_015',
 'FOODS_3_016',
 'FOODS_3_017',
 'FOODS_3_018',
 'FOODS_3_019',
 'FOODS_3_020',
 'FOODS_3_021',
 'FOODS_3_022',
 'FOODS_3_023',
 'FOODS_3_024',
 'FOODS_3_025',
 'FOODS_3_026',
 'FOODS_3_027',
 'FOODS_3_028',
 'FOODS_3_029',
 'FOODS_3_030',
 'FOODS_3_031',
 'FOODS_3_032',
 'FOODS_3_033',
 'FOODS_3_034',
 'FOODS_3_035',
 'FOODS_3_036',
 'FOODS_3_037',
 'FOODS_3_038',
 'FOODS_3_039',
 'FOODS_3_040',
 'FOODS_3_041',
 'FOODS_3_042',
 'FOODS_3_043',
 'FOODS_3_044',
 'FOODS_3_045',
 'FOODS_3_046',
 'FOODS_3_047',
 'FOODS_3_048',
 'FOODS_3_049',
 'FOODS_3_050',
 'FOODS_3_051',
 'FOODS_3_053',
 'FOODS_3_054',
 'FOODS_3_055',
 'FOODS_3_056',
 'FOODS_3_057',
 'FOODS_3_058',
 'FOODS_3_059',
 'FOODS_3_060',
 'FOODS_3_061',
 'FOODS_3_062',
 'FOODS_3_063',
 'FOODS_3_064',
 'FOODS_3_065',
 'FOODS_3_066',
 'FOODS_3_067',
 'FOODS_3_068',
 'FOODS_3_069',
 'FOODS_3_070',
 'FOODS_3_071',
 'FOODS_3_072',
 'FOODS_3_073',
 'FOODS_3_074',
 'FOODS_3_075',
 'FOODS_3_076',
 'FOODS_3_077',
 'FOODS_3_078',
 'FOODS_3_079',
 'FOODS_3_080',
 'FOODS_3_081',
 'FOODS_3_082',
 'FOODS_3_083',
 'FOODS_3_084',
 'FOODS_3_085',
 'FOODS_3_086',
 'FOODS_3_087',
 'FOODS_3_088',
 'FOODS_3_089',
 'FOODS_3_090',
 'FOODS_3_091',
 'FOODS_3_092',
 'FOODS_3_093',
 'FOODS_3_094',
 'FOODS_3_095',
 'FOODS_3_096',
 'FOODS_3_097',
 'FOODS_3_098',
 'FOODS_3_099',
 'FOODS_3_100',
 'FOODS_3_101',
 'FOODS_3_102',
 'FOODS_3_103',
 'FOODS_3_104',
 'FOODS_3_105',
 'FOODS_3_106',
 'FOODS_3_107',
 'FOODS_3_108',
 'FOODS_3_109',
 'FOODS_3_110',
 'FOODS_3_111',
 'FOODS_3_112',
 'FOODS_3_113',
 'FOODS_3_114',
 'FOODS_3_115',
 'FOODS_3_116',
 'FOODS_3_117',
 'FOODS_3_118',
 'FOODS_3_119',
 'FOODS_3_120',
 'FOODS_3_121',
 'FOODS_3_122',
 'FOODS_3_123',
 'FOODS_3_124',
 'FOODS_3_125',
 'FOODS_3_126',
 'FOODS_3_127',
 'FOODS_3_128',
 'FOODS_3_129',
 'FOODS_3_130',
 'FOODS_3_131',
 'FOODS_3_132',
 'FOODS_3_133',
 'FOODS_3_134',
 'FOODS_3_135',
 'FOODS_3_136',
 'FOODS_3_137',
 'FOODS_3_138',
 'FOODS_3_139',
 'FOODS_3_140',
 'FOODS_3_141',
 'FOODS_3_142',
 'FOODS_3_143',
 'FOODS_3_144',
 'FOODS_3_145',
 'FOODS_3_146',
 'FOODS_3_147',
 'FOODS_3_148',
 'FOODS_3_149',
 'FOODS_3_150',
 'FOODS_3_151',
 'FOODS_3_152',
 'FOODS_3_153',
 'FOODS_3_154',
 'FOODS_3_155',
 'FOODS_3_156',
 'FOODS_3_157',
 'FOODS_3_158',
 'FOODS_3_159',
 'FOODS_3_160',
 'FOODS_3_161',
 'FOODS_3_162',
 'FOODS_3_163',
 'FOODS_3_164',
 'FOODS_3_165',
 'FOODS_3_166',
 'FOODS_3_167',
 'FOODS_3_168',
 'FOODS_3_169',
 'FOODS_3_170',
 'FOODS_3_171',
 'FOODS_3_172',
 'FOODS_3_173',
 'FOODS_3_174',
 'FOODS_3_175',
 'FOODS_3_176',
 'FOODS_3_177',
 'FOODS_3_178',
 'FOODS_3_179',
 'FOODS_3_180',
 'FOODS_3_181',
 'FOODS_3_182',
 'FOODS_3_183',
 'FOODS_3_184',
 'FOODS_3_185',
 'FOODS_3_186',
 'FOODS_3_187',
 'FOODS_3_188',
 'FOODS_3_189',
 'FOODS_3_190',
 'FOODS_3_191',
 'FOODS_3_192',
 'FOODS_3_193',
 'FOODS_3_194',
 'FOODS_3_195',
 'FOODS_3_196',
 'FOODS_3_197',
 'FOODS_3_198',
 'FOODS_3_199',
 'FOODS_3_200',
 'FOODS_3_201',
 'FOODS_3_202',
 'FOODS_3_203',
 'FOODS_3_204',
 'FOODS_3_205',
 'FOODS_3_206',
 'FOODS_3_207',
 'FOODS_3_208',
 'FOODS_3_209',
 'FOODS_3_210',
 'FOODS_3_211',
 'FOODS_3_212',
 'FOODS_3_213',
 'FOODS_3_214',
 'FOODS_3_215',
 'FOODS_3_216',
 'FOODS_3_217',
 'FOODS_3_218',
 'FOODS_3_219',
 'FOODS_3_220',
 'FOODS_3_221',
 'FOODS_3_222',
 'FOODS_3_223',
 'FOODS_3_224',
 'FOODS_3_225',
 'FOODS_3_226',
 'FOODS_3_227',
 'FOODS_3_228',
 'FOODS_3_229',
 'FOODS_3_230',
 'FOODS_3_231',
 'FOODS_3_232',
 'FOODS_3_233',
 'FOODS_3_234',
 'FOODS_3_235',
 'FOODS_3_236',
 'FOODS_3_237',
 'FOODS_3_238',
 'FOODS_3_239',
 'FOODS_3_240',
 'FOODS_3_241',
 'FOODS_3_242',
 'FOODS_3_243',
 'FOODS_3_244',
 'FOODS_3_245',
 'FOODS_3_246',
 'FOODS_3_247',
 'FOODS_3_248',
 'FOODS_3_249',
 'FOODS_3_250',
 'FOODS_3_251',
 'FOODS_3_252',
 'FOODS_3_253',
 'FOODS_3_254',
 'FOODS_3_255',
 'FOODS_3_256',
 'FOODS_3_257',
 'FOODS_3_258',
 'FOODS_3_259',
 'FOODS_3_260',
 'FOODS_3_261',
 'FOODS_3_262',
 'FOODS_3_263',
 'FOODS_3_264',
 'FOODS_3_265',
 'FOODS_3_266',
 'FOODS_3_267',
 'FOODS_3_268',
 'FOODS_3_269',
 'FOODS_3_270',
 'FOODS_3_271',
 'FOODS_3_272',
 'FOODS_3_273',
 'FOODS_3_274',
 'FOODS_3_275',
 'FOODS_3_276',
 'FOODS_3_277',
 'FOODS_3_278',
 'FOODS_3_279',
 'FOODS_3_280',
 'FOODS_3_281',
 'FOODS_3_282',
 'FOODS_3_283',
 'FOODS_3_284',
 'FOODS_3_285',
 'FOODS_3_286',
 'FOODS_3_287',
 'FOODS_3_288',
 'FOODS_3_289',
 'FOODS_3_290',
 'FOODS_3_291',
 'FOODS_3_292',
 'FOODS_3_293',
 'FOODS_3_294',
 'FOODS_3_295',
 'FOODS_3_296',
 'FOODS_3_297',
 'FOODS_3_298',
 'FOODS_3_299',
 'FOODS_3_300',
 'FOODS_3_301',
 'FOODS_3_302',
 'FOODS_3_303',
 'FOODS_3_304',
 'FOODS_3_305',
 'FOODS_3_306',
 'FOODS_3_307',
 'FOODS_3_308',
 'FOODS_3_309',
 'FOODS_3_310',
 'FOODS_3_311',
 'FOODS_3_312',
 'FOODS_3_313',
 'FOODS_3_314',
 'FOODS_3_315',
 'FOODS_3_316',
 'FOODS_3_317',
 'FOODS_3_318',
 'FOODS_3_319',
 'FOODS_3_320',
 'FOODS_3_321',
 'FOODS_3_322',
 'FOODS_3_323',
 'FOODS_3_324',
 'FOODS_3_325',
 'FOODS_3_326',
 'FOODS_3_327',
 'FOODS_3_328',
 'FOODS_3_329',
 'FOODS_3_330',
 'FOODS_3_331',
 'FOODS_3_332',
 'FOODS_3_333',
 'FOODS_3_334',
 'FOODS_3_335',
 'FOODS_3_336',
 'FOODS_3_337',
 'FOODS_3_338',
 'FOODS_3_339',
 'FOODS_3_340',
 'FOODS_3_341',
 'FOODS_3_342',
 'FOODS_3_343',
 'FOODS_3_344',
 'FOODS_3_345',
 'FOODS_3_346',
 'FOODS_3_347',
 'FOODS_3_348',
 'FOODS_3_349',
 'FOODS_3_350',
 'FOODS_3_351',
 'FOODS_3_352',
 'FOODS_3_353',
 'FOODS_3_354',
 'FOODS_3_355',
 'FOODS_3_356',
 'FOODS_3_357',
 'FOODS_3_358',
 'FOODS_3_359',
 'FOODS_3_360',
 'FOODS_3_361',
 'FOODS_3_362',
 'FOODS_3_363',
 'FOODS_3_364',
 'FOODS_3_365',
 'FOODS_3_366',
 'FOODS_3_367',
 'FOODS_3_368',
 'FOODS_3_369',
 'FOODS_3_370',
 'FOODS_3_371',
 'FOODS_3_372',
 'FOODS_3_373',
 'FOODS_3_374',
 'FOODS_3_375',
 'FOODS_3_376',
 'FOODS_3_377',
 'FOODS_3_378',
 'FOODS_3_379',
 'FOODS_3_380',
 'FOODS_3_381',
 'FOODS_3_382',
 'FOODS_3_383',
 'FOODS_3_384',
 'FOODS_3_385',
 'FOODS_3_386',
 'FOODS_3_387',
 ...]

In [4]:
OrderTd = []
for name in MODEL_NAMES:
    print(f"------------------------{name} Start!------------------------")
    df_name_orders = base_all.loc[base_all['name'] == name, on].reset_index(drop=True)
    df_name = pd.concat([ts2[['unique_id', 'ds']].reset_index(drop=True), df_name_orders], axis=1)

    per_prod = []
    for prod in tqdm(prods, leave=False):
        b = df_name[df_name['unique_id'].str.contains(prod)].copy()
        b['_row'] = b.index

        bs = s[s['unique_id'].str.contains(prod)].copy().reset_index(drop=True)
        bss = pd.concat(
            [bs[['unique_id']], bs.loc[:, bs.columns.str.contains(prod)].reset_index(drop=True)],
            axis=1,
        )

        uid_list = bs['unique_id'].tolist()
        btags = {
            l10_12[0]: [u for u in uid_list if len(u.split('/')) == 4],
            l10_12[1]: [u for u in uid_list if len(u.split('/')) == 5],
            l10_12[2]: [u for u in uid_list if len(u.split('/')) == 6],
        }

        rec = TDFP.reconcile(
            Y_hat_df=b[['unique_id', 'ds', 'ot_90', 'ot_95', 'ot_99']],
            S=bss,
            tags=btags,
        )[['unique_id', 'ds', 'ot_90/TopDown_method-forecast_proportions', 
             'ot_95/TopDown_method-forecast_proportions', 'ot_99/TopDown_method-forecast_proportions']]

        rec = rec.merge(b[['unique_id', 'ds', '_row']], on=['unique_id', 'ds'], how='left').sort_values('_row')
        per_prod.append(rec)

    rec_name = pd.concat(per_prod, ignore_index=True).sort_values('_row').drop(columns='_row').reset_index(drop=True)
    rec_name.insert(0, 'name', name)
    OrderTd.append(rec_name)

OrderTDFP = pd.concat(OrderTd, ignore_index=True)

------------------------lgb_base Start!------------------------

------------------------lgb_bu Start!------------------------

------------------------lgb_td Start!------------------------

------------------------lgb_mint Start!------------------------

------------------------ets_base Start!------------------------

------------------------ets_bu Start!------------------------

------------------------ets_td Start!------------------------

------------------------ets_mint Start!------------------------

In [5]:
OrderTDFP.columns = ['name', 'unique_id', 'ds']+on
OrderTDFP2 = OrderTDFP[['name']+on]
save_pickle(OrderTDFP2, f"OrderTDFP_L{lead_time}.pkl")
OrderTDFP2.head()

       name     ot_90     ot_95      ot_99
0  lgb_base  5.648312  7.249530  10.253148
1  lgb_base  2.989336  2.989336   2.989336
2  lgb_base  5.119798  5.119798   5.119798
3  lgb_base  8.181289  8.181289   8.181289
4  lgb_base  0.068346  0.068346   0.068346

In [6]:
Invt_df = []
OrderTDFP = OrderTDFP2.copy()
for name in MODEL_NAMES:
    base_ref = base_all.loc[base_all['name'] == name].reset_index(drop=True)
    order_ref = OrderTDFP.loc[OrderTDFP['name'] == name].reset_index(drop=True)

    fixed_orders = pd.concat(
        [
            base_ref[['forecasts', 'sst_90', 'sst_95', 'sst_99']].reset_index(drop=True),
            order_ref[['ot_90', 'ot_95', 'ot_99']].reset_index(drop=True),
        ],
        axis=1,
    )

    df = run_fixed_loop(
        truth=truth,
        forecast_source=base_ref['forecasts'].reset_index(drop=True),
        fixed_orders=fixed_orders,
        NAME=name,
        L_=lead_time,
    )
    Invt_df.append(df)

TDFPOrder = pd.concat(Invt_df, ignore_index=True)
save_pickle(TDFPOrder, f"TDFPOrder_L{lead_time}.pkl")
TDFPOrder.head()

100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:14<00:00, 573.34it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 580.68it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 581.52it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 583.26it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 579.62it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 580.35it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 576.92it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:13<00:00, 582.91it/s]

,name,true_demand,forecasts,sst_90,arrival_90,ot_90,wip_90,ip_90,net_90,backlog_90,...,cb_95,sst_99,arrival_99,ot_99,wip_99,ip_99,net_99,backlog_99,ch_99,cb_99
0,lgb_base,4.0,5.689794,5.648312,0.000000,5.648312,5.648312,7.338106,1.689794,0.000000,...,0.000000,10.253148,0.000000,10.253148,10.253148,11.942942,1.689794,0.0,1.689794,0.0
1,lgb_base,5.0,4.679130,5.648312,5.648312,2.989336,2.989336,5.327442,2.338106,0.000000,...,0.000000,10.253148,10.253148,2.989336,2.989336,9.932278,6.942942,0.0,6.942942,0.0
2,lgb_base,7.0,4.798928,5.648312,2.989336,5.119798,5.119798,3.447240,-1.672558,1.672558,...,1.355461,10.253148,2.989336,5.119798,5.119798,8.052076,2.932278,0.0,2.932278,0.0
3,lgb_base,1.0,5.980217,5.648312,5.119798,8.181289,8.181289,10.628529,2.447240,0.000000,...,0.000000,10.253148,5.119798,8.181289,8.181289,15.233366,7.052076,0.0,7.052076,0.0
4,lgb_base,9.0,5.048564,5.648312,8.181289,0.068346,0.068346,1.696875,1.628529,0.000000,...,0.000000,10.253148,8.181289,0.068346,0.068346,6.301712,6.233366,0.0,6.233366,0.0