## BASE

Forecast-based simulation with the cleaned pipeline modules.

In [1]:
path1 = 'E:/yjz/Extension for hts/JayCode/Models/'

import warnings
warnings.simplefilter("ignore")

import numpy as np
import pandas as pd
from inventory_pipeline import run_base_loop, save_pickle

In [2]:
fcst = pd.read_pickle(f"{path1}721fcsts_base2cohe.pkl").reset_index(drop=True)
fitt = pd.read_pickle(f"{path1}721fitts_base2cohe.pkl").reset_index(drop=True)

test = pd.read_pickle(f"{path1}721future_28.pkl").reset_index(drop=True)
truth = test['y'].reset_index(drop=True)
history = pd.read_pickle(f"{path1}721past_1913.pkl").reset_index(drop=True)

etsf = fitt.iloc[:, 4:].reset_index(drop=True)
lgbf = fitt.iloc[:, :4].reset_index(drop=True)

ets_resid = pd.concat({etsf.columns[i]: history['y'] - etsf.iloc[:, i] for i in range(4)}, axis=1).reset_index(drop=True)
lgb_resid = pd.concat({lgbf.columns[i]: history['y'] - lgbf.iloc[:, i] for i in range(4)}, axis=1).reset_index(drop=True)

LGB_NAMES = ['lgb_base', 'lgb_bu', 'lgb_td', 'lgb_mint']
ETS_NAMES = ['ets_base', 'ets_bu', 'ets_td', 'ets_mint']

In [3]:
len([0]*len(truth))

1195208

In [4]:
81658318/1913

42686.0

In [5]:
lead_time = 1

Invt_df = []
for name in range(1):#LGB_NAMES:
    Invt_df.append(run_base_loop(fcst=truth, truth=truth, residual=np.array([0]*len(ets_resid)), NAME=name, L_=lead_time))
lgbInvtSim = pd.concat(Invt_df, ignore_index=True)
save_pickle(lgbInvtSim, f"lgbInvtSim_L{lead_time}_ideal.pkl")

Invt_df = []
for name in  range(1):#ETS_NAMES[0]:
    Invt_df.append(run_base_loop(fcst=truth, truth=truth, residual=np.array([0]*len(ets_resid)), NAME=name, L_=lead_time))
etsInvtSim = pd.concat(Invt_df, ignore_index=True)
save_pickle(etsInvtSim, f"etsInvtSim_L{lead_time}_ideal.pkl")

lgbInvtSim.head()

100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:25<00:00, 501.98it/s]
100%|███████████████████████████████████████████████████████████████████████████| 42686/42686 [01:25<00:00, 501.69it/s]

,name,true_demand,forecasts,sst_90,arrival_90,ot_90,wip_90,ip_90,net_90,backlog_90,...,cb_95,sst_99,arrival_99,ot_99,wip_99,ip_99,net_99,backlog_99,ch_99,cb_99
0,0,4.0,4.0,0.0,0.0,5.0,5.0,5.0,0.0,0.0,...,0.0,0.0,0.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
1,0,5.0,5.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,...,0.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
2,0,7.0,7.0,0.0,7.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,7.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
3,0,1.0,1.0,0.0,1.0,9.0,9.0,9.0,0.0,0.0,...,0.0,0.0,1.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
4,0,9.0,9.0,0.0,9.0,3.0,3.0,3.0,0.0,0.0,...,0.0,0.0,9.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0

In [6]:
lgbInvtSim.iloc[:28,]

,name,true_demand,forecasts,sst_90,arrival_90,ot_90,wip_90,ip_90,net_90,backlog_90,...,cb_95,sst_99,arrival_99,ot_99,wip_99,ip_99,net_99,backlog_99,ch_99,cb_99
0,0,4.0,4.0,0.0,0.0,5.0,5.0,5.0,0.0,0.0,...,0.0,0.0,0.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
1,0,5.0,5.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,...,0.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
2,0,7.0,7.0,0.0,7.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,7.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
3,0,1.0,1.0,0.0,1.0,9.0,9.0,9.0,0.0,0.0,...,0.0,0.0,1.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
4,0,9.0,9.0,0.0,9.0,3.0,3.0,3.0,0.0,0.0,...,0.0,0.0,9.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0
5,0,3.0,3.0,0.0,3.0,9.0,9.0,9.0,0.0,0.0,...,0.0,0.0,3.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
6,0,9.0,9.0,0.0,9.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,9.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
7,0,1.0,1.0,0.0,1.0,10.0,10.0,10.0,0.0,0.0,...,0.0,0.0,1.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0
8,0,10.0,10.0,0.0,10.0,3.0,3.0,3.0,0.0,0.0,...,0.0,0.0,10.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0
9,0,3.0,3.0,0.0,3.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,3.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
10,0,1.0,1.0,0.0,1.0,6.0,6.0,6.0,0.0,0.0,...,0.0,0.0,1.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0
11,0,6.0,6.0,0.0,6.0,10.0,10.0,10.0,0.0,0.0,...,0.0,0.0,6.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0
12,0,10.0,10.0,0.0,10.0,6.0,6.0,6.0,0.0,0.0,...,0.0,0.0,10.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0
13,0,6.0,6.0,0.0,6.0,2.0,2.0,2.0,0.0,0.0,...,0.0,0.0,6.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0
14,0,2.0,2.0,0.0,2.0,5.0,5.0,5.0,0.0,0.0,...,0.0,0.0,2.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
15,0,5.0,5.0,0.0,5.0,6.0,6.0,6.0,0.0,0.0,...,0.0,0.0,5.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0
16,0,6.0,6.0,0.0,6.0,2.0,2.0,2.0,0.0,0.0,...,0.0,0.0,6.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0
17,0,2.0,2.0,0.0,2.0,7.0,7.0,7.0,0.0,0.0,...,0.0,0.0,2.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
18,0,7.0,7.0,0.0,7.0,8.0,8.0,8.0,0.0,0.0,...,0.0,0.0,7.0,8.0,8.0,8.0,0.0,0.0,0.0,0.0
19,0,8.0,8.0,0.0,8.0,8.0,8.0,8.0,0.0,0.0,...,0.0,0.0,8.0,8.0,8.0,8.0,0.0,0.0,0.0,0.0
20,0,8.0,8.0,0.0,8.0,4.0,4.0,4.0,0.0,0.0,...,0.0,0.0,8.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0
21,0,4.0,4.0,0.0,4.0,7.0,7.0,7.0,0.0,0.0,...,0.0,0.0,4.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
22,0,7.0,7.0,0.0,7.0,7.0,7.0,7.0,0.0,0.0,...,0.0,0.0,7.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
23,0,7.0,7.0,0.0,7.0,5.0,5.0,5.0,0.0,0.0,...,0.0,0.0,7.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
24,0,5.0,5.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,...,0.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
25,0,7.0,7.0,0.0,7.0,5.0,5.0,5.0,0.0,0.0,...,0.0,0.0,7.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
26,0,5.0,5.0,0.0,5.0,9.0,9.0,9.0,0.0,0.0,...,0.0,0.0,5.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
27,0,9.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
import pandas as pd
lead_time = 1
a = pd.read_pickle(f"etsInvtSim_L{lead_time}.pkl")
# a.to_csv("")
# a.iloc[:50,:]
a.iloc[:28, :12].to_csv(f"FOODS_1_001(TOTAL)_etsInvtSim.csv", index = False)

In [8]:
a = pd.read_pickle(f"lgbInvtSim_L{lead_time}_ideal.pkl")
a.iloc[:28, :12].to_csv(f"FOODS_1_001(TOTAL)_lgbInvtSim_ideal.csv", index = False)

In [9]:
a.iloc[:28, :12]

,name,true_demand,forecasts,sst_90,arrival_90,ot_90,wip_90,ip_90,net_90,backlog_90,ch_90,cb_90
0,0,4.0,4.0,0.0,0.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
1,0,5.0,5.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
2,0,7.0,7.0,0.0,7.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
3,0,1.0,1.0,0.0,1.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
4,0,9.0,9.0,0.0,9.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0
5,0,3.0,3.0,0.0,3.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
6,0,9.0,9.0,0.0,9.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
7,0,1.0,1.0,0.0,1.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0
8,0,10.0,10.0,0.0,10.0,3.0,3.0,3.0,0.0,0.0,0.0,0.0
9,0,3.0,3.0,0.0,3.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
10,0,1.0,1.0,0.0,1.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0
11,0,6.0,6.0,0.0,6.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0
12,0,10.0,10.0,0.0,10.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0
13,0,6.0,6.0,0.0,6.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0
14,0,2.0,2.0,0.0,2.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
15,0,5.0,5.0,0.0,5.0,6.0,6.0,6.0,0.0,0.0,0.0,0.0
16,0,6.0,6.0,0.0,6.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0
17,0,2.0,2.0,0.0,2.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
18,0,7.0,7.0,0.0,7.0,8.0,8.0,8.0,0.0,0.0,0.0,0.0
19,0,8.0,8.0,0.0,8.0,8.0,8.0,8.0,0.0,0.0,0.0,0.0
20,0,8.0,8.0,0.0,8.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0
21,0,4.0,4.0,0.0,4.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
22,0,7.0,7.0,0.0,7.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
23,0,7.0,7.0,0.0,7.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
24,0,5.0,5.0,0.0,5.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0
25,0,7.0,7.0,0.0,7.0,5.0,5.0,5.0,0.0,0.0,0.0,0.0
26,0,5.0,5.0,0.0,5.0,9.0,9.0,9.0,0.0,0.0,0.0,0.0
27,0,9.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
import pandas as pd
pd.read_csv("FOODS_1_001(TOTAL)_lgbInvtSim.csv")

,name,true_demand,forecasts,sst_90,arrival_90,ot_90,wip_90,ip_90,net_90,backlog_90,ch_90,cb_90
0,lgb_base,4.0,5.689794,5.648312,0.000000,5.648312,5.648312,7.338106,1.689794,0.000000,1.689794,0.000000
1,lgb_base,5.0,4.679130,5.648312,5.648312,2.989336,2.989336,5.327442,2.338106,0.000000,2.338106,0.000000
2,lgb_base,7.0,4.798928,5.648312,2.989336,5.119798,5.119798,3.447240,-1.672558,1.672558,0.000000,15.053022
3,lgb_base,1.0,5.980217,5.648312,5.119798,8.181289,8.181289,10.628529,2.447240,0.000000,2.447240,0.000000
4,lgb_base,9.0,5.048564,5.648312,8.181289,0.068346,0.068346,1.696875,1.628529,0.000000,1.628529,0.000000
5,lgb_base,3.0,8.247916,5.648312,0.068346,12.199352,12.199352,10.896228,-1.303125,1.303125,0.000000,11.728121
6,lgb_base,9.0,6.159383,5.648312,12.199352,0.911468,0.911468,2.807695,1.896228,0.000000,1.896228,0.000000
7,lgb_base,1.0,6.263591,5.648312,0.911468,9.104207,9.104207,10.911902,1.807695,0.000000,1.807695,0.000000
8,lgb_base,10.0,4.828214,5.648312,9.104207,0.000000,0.000000,0.911902,0.911902,0.000000,0.911902,0.000000
9,lgb_base,3.0,6.094202,5.648312,0.000000,10.830611,10.830611,8.742514,-2.088098,2.088098,0.000000,18.792878
10,lgb_base,1.0,5.031809,5.648312,10.830611,1.937607,1.937607,9.680121,7.742514,0.000000,7.742514,0.000000
11,lgb_base,6.0,4.941603,5.648312,1.937607,0.909794,0.909794,4.589915,3.680121,0.000000,3.680121,0.000000
12,lgb_base,10.0,5.502819,5.648312,0.909794,6.561215,6.561215,1.151130,-5.410085,5.410085,0.000000,48.690763
13,lgb_base,6.0,6.812643,5.648312,6.561215,11.309825,11.309825,6.460955,-4.848870,4.848870,0.000000,43.639826
14,lgb_base,2.0,5.509732,5.648312,11.309825,4.697089,4.697089,9.158044,4.460955,0.000000,4.460955,0.000000
15,lgb_base,5.0,4.489056,5.648312,4.697089,0.979324,0.979324,5.137368,4.158044,0.000000,4.158044,0.000000
16,lgb_base,6.0,4.036600,5.648312,0.979324,4.547544,4.547544,3.684911,-0.862632,0.862632,0.000000,7.763688
17,lgb_base,2.0,4.277162,5.648312,4.547544,6.240562,6.240562,7.925473,1.684911,0.000000,1.684911,0.000000
18,lgb_base,7.0,4.937993,5.648312,6.240562,2.660831,2.660831,3.586305,0.925473,0.000000,0.925473,0.000000
19,lgb_base,8.0,6.986690,5.648312,2.660831,9.048697,9.048697,4.635002,-4.413695,4.413695,0.000000,39.723258
20,lgb_base,8.0,6.820887,5.648312,9.048697,7.834197,7.834197,4.469199,-3.364998,3.364998,0.000000,30.284984
21,lgb_base,4.0,5.335919,5.648312,7.834197,6.515032,6.515032,6.984231,0.469199,0.000000,0.469199,0.000000
22,lgb_base,7.0,5.285314,5.648312,6.515032,3.949395,3.949395,3.933626,-0.015769,0.015769,0.000000,0.141922
23,lgb_base,7.0,5.895731,5.648312,3.949395,7.610417,7.610417,4.544043,-3.066374,3.066374,0.000000,27.597367
24,lgb_base,5.0,6.081204,5.648312,7.610417,7.185473,7.185473,6.729516,-0.455957,0.455957,0.000000,4.103614
25,lgb_base,7.0,6.406713,5.648312,7.185473,5.325510,5.325510,5.055025,-0.270484,0.270484,0.000000,2.434360
26,lgb_base,5.0,7.593174,5.648312,5.325510,8.186460,8.186460,8.241486,0.055025,0.000000,0.055025,0.000000
27,lgb_base,9.0,6.884840,5.648312,8.186460,4.291666,4.291666,3.533152,-0.758514,0.758514,0.000000,6.826629